name: CI
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: ./build.sh && cat package.json
      - uses: AkhileshNS/heroku-deploy@v3.5.6
        with :  
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "githubactions" #Must be unique in Heroku
          heroku_email: "41sukhdevsingh@gmail.com"
