name: CI
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1000
          repository: sukhiboi/blog-backend
      - name: Testing Backend
        run: |
          npm install;
          npm test;
      - uses: actions/checkout@v2
        with:
          repository: sukhiboi/blog-frontend
          path: frontend
      - name: Building frontend
        run: |
          cd frontend;
          npm install;
          npm run build;
          mv build ..;
          cd ..;
          rm -rf frontend;
      - name: Deploy to Heroku
        run: ls -al && echo "react build" && ls -al build;
