name: CI
on:
  push:
    branches: [master]
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Test
          run: pwd && npm install && npm test
    anotherTest:
      runs-on: ubuntu-latest
      steps:
        - name: hi
          run: pwd && npm test
