name: CI
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: ls && pwd && npm install && npm test
  anotherTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hi
        run: ls && pwd && npm test
